services:
  devpi:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${DEVPI_PORT:-3141}:3141"
    volumes:
      - "${DEVPI_HOME:-./devpi}:/root/.devpi"
    tty: true
    stdin_open: true
